server.port=8081

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/stage}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:2005}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

openrouter.base-url=${OPENROUTER_BASE_URL:https://openrouter.ai/api/v1}
openrouter.model=${OPENROUTER_MODEL:openrouter/free}
openrouter.api-key=${OPENROUTER_API_KEY:}
